# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: sugar
version: '0.0.0'
github: "jxv/sugar"
license: MIT
author: "Joe Vargas"
maintainer: "Joe Vargas"
# synopsis: A new Haskeleton package.
# description: sugar is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - containers
  - megaparsec
  - text
  source-dirs: library
  default-extensions:
  - OverloadedStrings
  - NamedFieldPuns

tests:
  sugar-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - sugar
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
